# Generated by Django 5.1.15 on 2026-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_expiry', models.DateField(help_text='License expiration date')),
                ('vehicle_category', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike'), ('all', 'All Categories')], default='van', help_text='Category of vehicles this driver can operate', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], db_index=True, default='available', max_length=15)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Safety score (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers_driver',
                'ordering': ['name'],
            },
        ),
    ]
