# Generated by Django 5.1.15 on 2026-02-21 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vehicle name/model (e.g. Van-05)', max_length=100)),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], default='van', max_length=10)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Max load capacity in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odometer', models.DecimalField(decimal_places=2, default=0, help_text='Current odometer reading in km', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('region', models.CharField(blank=True, default='', help_text='Operating region', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], db_index=True, default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fleet_vehicle',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='vehicle_capacity_positive'), models.CheckConstraint(condition=models.Q(('odometer__gte', 0)), name='vehicle_odometer_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('engine_repair', 'Engine Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_maintenance',
                'ordering': ['-date'],
            },
        ),
    ]
