# Generated by Django 5.1.15 on 2026-07-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_plate',
            new_name='registration_number',
        ),
    ]
