# Generated by Django 5.1.15 on 2026-02-21 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Cargo weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'operations_trip',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cargo_weight__gt', 0)), name='trip_cargo_weight_positive')],
            },
        ),
    ]
