# Generated by Django 5.1.15 on 2026-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='origin',
            new_name='source',
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected length of the trip before dispatch in km', max_digits=10, null=True),
        ),
    ]
